### ISSUE TITLE
How to contact the team

### ISSUE THREAD

**Issue by RdeWilde** [Viewly/platform-contracts#7]
How can one contact the Viewly team besides Telegram?

**Comment by Netherdrake** [comment]
support@view.ly

**Comment by RdeWilde** [comment]
No reponse, neither on mail nor linkedin nor telegram nor whatever i try. :-1:

**Comment by Netherdrake** [comment]
We don't use LinkedIn.
Telegram is riddled with trolls; we are building a new group on Discord instead: https://discordapp.com/invite/MkTqjnG

**Comment by RdeWilde** [comment]
Though you have been online...

And let me guess, e-mail doesn't work either?

**Comment by Netherdrake** [comment]
Email works. We also have a contact form: https://viewly.typeform.com/to/eGUK0a

**Comment by RdeWilde** [comment]
Then I am simply being ignored. Please unblock me from Telegram

**Comment by ViewlySupport** [comment]
Hi there,

An email was sent to you last week, please check inbox / spam folders for support email and follow the instructions.

Thank you.
